### ISSUE TITLE
Got the displayed error in the task page in which the task is "new" or "running" state

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-robot-portal#1]
![sc1](https://user-images.githubusercontent.com/15011431/41966649-f1ade828-79ff-11e8-9afe-e0fb1df8024b.png)

**Comment by john-kheir** [comment]
Also sometimes when a task is in error, i get this:

```
Error: no such item for Cursor instance
```

**Comment by alichaddad** [comment]
Fixed in https://github.com/zero-os/0-robot-portal/commit/cf1a67029d6b6ba84753b1caac998fe8a3a8c29b
